version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: secret
    ports:
      - "5555:5432"

  todo-service:
    image: ghcr.io/mrvxk/middleware-todo-native-service:latest
    container_name: todo-service
    environment:
      HTTP_PORT: 8080 # default is also 8080
      DB_URL: postgres
      DB_PORT: 5432
      DB_NAME: db
      DB_USERNAME: postgres
      DB_PASSWORD: secret
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  todo-ui:
    image: ghcr.io/mrvxk/middleware-todo-ui:latest
    container_name: todo-ui
    ports:
      - "4200:80"
    depends_on:
      - todo-service
