quarkus:
  hibernate-orm:
      database:
        generation: create
  datasource:
    jdbc:
      url: jdbc:postgresql://postgres:5432/db
    username: postgres
    password: secret
  http:
    cors:
      ~: true
      origins: "*"
  swagger-ui:
    always-include: true
