quarkus:
  hibernate-orm:
      database:
        generation: update
  datasource:
    jdbc:
      url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  http:
    port: ${HTTP_PORT:8080}
    cors:
      ~: true
      origins: ${CORS_ORIGINS}
  swagger-ui:
    always-include: true
