name: UI Docker Image Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'todo-service/**'
  workflow_dispatch:
concurrency: production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.key }}

      - name: Install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildx-version: latest

      - name: Build Docker Image
        run: |
          docker buildx build --push \
          --platform linux/amd64,linux/arm64 \
          --tag ghcr.io/mrvxk/middleware-todo-ui:latest \
          --file ./todo-ui/Dockerfile ./todo-ui