name: Quarkus Native Docker Image Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'todo-infra/**'
      - 'README.md'
      - 'todo-ui/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm' # See 'Options' for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print java / graalvm path setup
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
               brew install docker
               colima start
          
          # For testcontainers to find the Colima socket
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
               sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.key }}

      - name: Build module packages with Maven
        run: mvn -B install -DskipTests -Dnative -Dquarkus.native.container-build=true -f todo-service/pom.xml

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest

      - name: Build the Docker image and push to github
        run: |
          docker buildx build --push \
          --tag ghcr.io/mrvxk/middleware-todo-native-service:latest \
          --file todo-service/src/main/docker/Dockerfile.native-micro \
          --platform linux/amd64,linux/arm64 ./todo-service
